# Generated by Django 4.1.7 on 2023-04-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='Имя пользователя')),
                ('name', models.CharField(max_length=300, verbose_name='Название товара')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('Молоко, яйца, масло', 'Молоко, яйца, масло'),
                            ('Мясо и птица', 'Мясо и птица'),
                            ('Выпечка', 'Выпечка'),
                            ('Бакалея', 'Бакалея'),
                            ('Полуфабрикаты', 'Полуфабрикаты'),
                            ('Напитки', 'Напитки'),
                            ('Чипсы, орехи, сухофрукты', 'Чипсы, орехи, сухофрукты'),
                        ],
                        max_length=50,
                        verbose_name='Категория',
                    ),
                ),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=150, verbose_name='Описание товара')),
                ('expiration_date', models.CharField(max_length=50, verbose_name='Срок годности')),
                ('image', models.ImageField(blank=True, upload_to='delivery/static/assets/food')),
            ],
        ),
    ]
