# Generated by Django 4.1.7 on 2023-03-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="catalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название товара"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Молочная продукция", "Молочная продукция"),
                            ("Мясная гастрономия", "Мясная гастрономия"),
                            ("Выпечка", "Выпечка"),
                            ("Бакалея", "Бакалея"),
                            ("Полуфабрикаты", "Полуфабрикаты"),
                            ("Напитки", "Напитки"),
                            ("Снеки", "Снеки"),
                        ],
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                ("price", models.FloatField()),
                (
                    "description",
                    models.CharField(max_length=150, verbose_name="Описание товара"),
                ),
                (
                    "expiration_date",
                    models.CharField(max_length=30, verbose_name="Срок годности"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="static/assets/food"),
                ),
            ],
        ),
    ]
