# Generated by Django 4.1.7 on 2023-04-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='image',
            field=models.ImageField(blank=True, upload_to='delivery/static/assets/food'),
        ),
        migrations.AddField(
            model_name='basket',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
