# Generated by Django 4.1.7 on 2023-04-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('delivery', '0002_basket_image_basket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
