# Generated by Django 4.1.7 on 2023-03-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "delivery",
            "0002_alter_catalog_category_alter_catalog_expiration_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="price",
            field=models.IntegerField(),
        ),
    ]
