# Generated by Django 4.1.7 on 2023-04-19 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0004_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.catalog'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
