# Generated by Django 4.1.7 on 2023-04-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_alter_basket_name_alter_basket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название товара'),
        ),
    ]
