# Generated by Django 4.1.7 on 2023-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_alter_basket_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.IntegerField(max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
