# Generated by Django 4.1.7 on 2023-04-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_cart_cartitem_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.IntegerField(verbose_name='Имя пользователя'),
        ),
    ]
